version: '3.9'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'tom'
      MYSQL_USER: 'tom'
      MYSQL_PASSWORD: 'tom123'
    ports:
      - '3306:3306'
    # fix mbind spam: https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
    cap_add:
      - SYS_NICE
